/**
 * Copyright 2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Program used to generate test pages for the Client URL Internet Emission
 * Sniffer (Curlies) project.
 *
 * @author Shaopeng Jia (jia.shao.peng@gmail.com)
 */

#include <stdio.h>

#include <iostream>
#include <string>
#include <vector>

#include "testcases.h"

using namespace std;

static void WriteFileHeader(FILE* output_file, const char* charset) {
  fprintf(output_file,
      "<!-- Copyright 2009 Google Inc.\n\n"
      "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
      "you may not use this file except in compliance with the License.\n"
      "You may obtain a copy of the License at\n\n"
      "     http://www.apache.org/licenses/LICENSE-2.0\n\n"
      "Unless required by applicable law or agreed to in writing, software\n"
      "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
      "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
      "See the License for the specific language governing permissions and\n"
      "limitations under the License.\n\n"
      "Author: Shaopeng Jia (jia.shao.peng@gmail.com)\n"
      "Author: Erik van der Poel (erikvanderpoel@gmail.com)\n\n"
      "Note: This file is automatically generated by\n"
      " ../source/test-page-generator.cc. If you want to add additional\n"
      "tests, please add it in the ../source/testcases.cc, or contact the authors.\n"
      "-->\n\n"
      "<html>\n"
      "<head>\n"
      "<meta http-equiv=\"Content-Type\" "
      "content=\"text/html; charset=%s\">\n"
      "</head>\n"
      "<body>\n", charset
      );
  fprintf(output_file, "<table border=\"1\">\n");
  fprintf(output_file, "<tr><td>Test ID</td><td>Test</td></tr>\n");
}

static void WriteFileFooter(FILE* output_file) {
  fprintf(output_file, "</table>\n");
  fprintf(output_file, "</body>\n");
  fprintf(output_file, "</html>\n");
}

static void GenerateTestCase(FILE* output_file, int id,
                             const char* prefix, const char* suffix,
                             const char* test_string,
                             const char* display_string, bool escaped) {
  if (strlen(test_string) <= 1) {
    int b = *test_string;
    fprintf(output_file,
            "<tr><td>%d</td><td>"
            "<img src=%chttp://%s9pz%d9pz9qz",
            id,
            b == '"' ? '\'' : '"', prefix,
            id);

    if (escaped) {
      fprintf(output_file, "%%%02X9qz", b);
    } else {
      fprintf(output_file, "%c9qz", b);
    }

    fprintf(output_file,
            "%s%c>%s%02X", suffix,
            b == '"' ? '\'' : '"',
            escaped ? "%" : "\\x", b);
    fprintf(output_file, "</td></tr>\n");
  } else {
    fprintf(output_file,
            "<tr><td>%d</td><td>"
            "<img src=\"http://%s9pz%d9pz9qz%s9qz%s\">%s"
            "</td></tr>\n",
            id,
            prefix, id, test_string, suffix,
            display_string);
  }
}

static void GenerateFormTestCase(FILE* output_file, int id,
                                 const char* test_string,
                                 const char* display_string, bool escaped,
                                 string* form_script) {
  char form_name[20];
  char frame_name[20];
  sprintf(form_name, "form%d", id);
  sprintf(frame_name, "frame%d", id);
  form_script->append("    document.");
  form_script->append(form_name);
  form_script->append(".submit();\n");

  fprintf(output_file,
          "<tr><td>%d</td> <td>%s</td>\n"
          "<td><form name='%s' method='get'"
          " action='http://google.com/gen_204' target='%s'>\n"
          "<input type='text' name='query' value=",
          id, display_string, form_name, frame_name);

  if (strlen(test_string) <= 1) {
    int b = *test_string;
    fprintf(output_file, "%c9pz%d9pz9qz",
            b == '"' ? '\'' : '"', id);
    if (escaped) {
      fprintf(output_file, "%%%02X9qz", b);
    } else {
      fprintf(output_file, "%c9qz", b);
    }
    fprintf(output_file, "%c", b == '"' ? '\'' : '"');
  } else {
    fprintf(output_file, "\'9pz%d9pz9qz%s9qz\'", id, test_string);
  }

  fprintf(output_file, " /></form>\n</td></tr>\n");
  fprintf(output_file,
          "<iframe name='%s' width='0' height='0' frameborder='0'>\n"
          "</iframe>\n", frame_name);
}

int main(int argc, const char* argv[]) {
  vector<FILE*> form(kEncodingSize);
  FILE* host_ascii_escaped =
      fopen("test_pages/host-ascii-escaped.html", "w");
  FILE* host_ascii_unescaped =
      fopen("test_pages/host-ascii-unescaped.html", "w");
  FILE* path_ascii_escaped =
      fopen("test_pages/path-ascii-escape.html", "w");
  FILE* path_ascii_unescaped =
      fopen("test_pages/path-ascii-unescape.html", "w");
  FILE* parameter_ascii_escaped =
      fopen("test_pages/parameter-ascii-escaped.html", "w");
  FILE* parameter_ascii_unescaped =
      fopen("test_pages/parameter-ascii-unescaped.html", "w");
  FILE* query_ascii_escaped =
      fopen("test_pages/query-ascii-escaped.html", "w");
  FILE* query_ascii_unescaped =
      fopen("test_pages/query-ascii-unescaped.html", "w");
  form[kAscii] =
      fopen("test_pages/form-ascii.html", "w");
  FILE* all_big5 =
      fopen("test_pages/all-big5.html", "w");
  form[kBig5] =
      fopen("test_pages/form-big5.html", "w");

  WriteFileHeader(host_ascii_escaped, "US-ASCII");
  WriteFileHeader(host_ascii_unescaped, "US-ASCII");
  WriteFileHeader(path_ascii_escaped, "US-ASCII");
  WriteFileHeader(path_ascii_unescaped, "US-ASCII");
  WriteFileHeader(parameter_ascii_escaped, "US-ASCII");
  WriteFileHeader(parameter_ascii_unescaped, "US-ASCII");
  WriteFileHeader(query_ascii_escaped, "US-ASCII");
  WriteFileHeader(query_ascii_unescaped, "US-ASCII");
  WriteFileHeader(form[kAscii], "US-ASCII");
  WriteFileHeader(all_big5, "big5");
  WriteFileHeader(form[kBig5], "big5");

  // First dimension denotes TestType, and second dimension denotes
  // whether it is escaped.
  FILE* file_matrix[][2] = {
    {host_ascii_unescaped, host_ascii_escaped},
    {path_ascii_unescaped, path_ascii_escaped},
    {parameter_ascii_unescaped, parameter_ascii_escaped},
    {query_ascii_unescaped, query_ascii_escaped},
    {form[kAscii], form[kAscii]},
  };
  // The index of the vector denotes Encoding.
  vector<string> form_script(kEncodingSize,
      "\n<script type='text/javascript'>\n"
      "  function myfunction() {\n");
  int num_of_test = entries_size();
  for (int index = 0; index < num_of_test; index++) {
    FILE* output_file;
    TestCase test_case = entries[index];
    TestType test_component = test_case.test_component;
    Encoding encoding = test_case.test_encoding;
    switch (encoding) {
      case kAscii:
        output_file = file_matrix[test_component][test_case.should_escape];
        break;
      case kBig5:
        switch (test_component) {
          case kFormGet:
            output_file = form[kBig5];
            break;
          default:
            output_file = all_big5;
        }
        break;
      default:
        cerr << "Unexpected test encoding: " << encoding;
    }

    string test_string = string(test_case.test_string);
    char buffer[30];
    sprintf(buffer, "%d.wildcard.invalid./", test_case.test_id);
    string prefix(buffer);
    switch (test_component) {
      case kHost:
        if (encoding != kAscii) {
          test_string = "." + test_string + ".";
        }
        GenerateTestCase(output_file, test_case.test_id,
                         "", ".wildcard.invalid./",
                         test_string.c_str(),
                         test_case.test_string_for_display,
                         test_case.should_escape);
        break;
      case kPath:
        GenerateTestCase(output_file, test_case.test_id,
                         prefix.c_str(), "",
                         test_string.c_str(),
                         test_case.test_string_for_display,
                         test_case.should_escape);
        break;
      case kQuery:
        prefix += "search?q=";
        GenerateTestCase(output_file, test_case.test_id,
                         prefix.c_str(), "",
                         test_string.c_str(),
                         test_case.test_string_for_display,
                         test_case.should_escape);
        break;
      case kParameter:
        prefix += "search;q=";
        GenerateTestCase(output_file, test_case.test_id,
                         prefix.c_str(), "",
                         test_string.c_str(),
                         test_case.test_string_for_display,
                         test_case.should_escape);
        break;
      case kFormGet:
        GenerateFormTestCase(output_file,
                             test_case.test_id,
                             test_case.test_string,
                             test_case.test_string_for_display,
                             test_case.should_escape,
                             &form_script[encoding]);
        break;
    }
  }

  for (int i = 0; i < kEncodingSize; i++) {
    form_script[i].append(
        "  }\n"
        "  window.onload = myfunction;\n"
        "</script>\n");
    fprintf(form[i], "%s", form_script[i].c_str());
  }
  WriteFileFooter(host_ascii_escaped);
  WriteFileFooter(host_ascii_unescaped);
  WriteFileFooter(path_ascii_escaped);
  WriteFileFooter(path_ascii_unescaped);
  WriteFileFooter(parameter_ascii_escaped);
  WriteFileFooter(parameter_ascii_unescaped);
  WriteFileFooter(query_ascii_escaped);
  WriteFileFooter(query_ascii_unescaped);
  WriteFileFooter(form[kAscii]);
  WriteFileFooter(all_big5);
  WriteFileFooter(form[kBig5]);

  fclose(host_ascii_escaped);
  fclose(host_ascii_unescaped);
  fclose(path_ascii_escaped);
  fclose(path_ascii_unescaped);
  fclose(parameter_ascii_escaped);
  fclose(parameter_ascii_unescaped);
  fclose(query_ascii_escaped);
  fclose(query_ascii_unescaped);
  fclose(form[kAscii]);
  fclose(all_big5);
  fclose(form[kBig5]);

  return 0;
}
